version: '2'
{%- if docker_cpu_count is defined %}
cpu_count: {{docker_cpu_count}}
{%- endif %}
{%- if docker_mem_limit is defined %}
mem_limit: {{docker_mem_limit}}
{%- endif %}
services:
  elasticsearch1:
    cap_add:
      - IPC_LOCK
    image: "{{docker_image}}:{{es_version}}"
    ports:
      - {{http_port}}:{{http_port}}
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - {{es_data_dir}}:/usr/share/elasticsearch/data
      - {{es_log_dir}}:/var/log/elasticsearch
{%- for host_path, docker_path in mounts.items() %}
      - {{host_path}}:{{docker_path}}
{%- endfor %}
